In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/concatenated_df.csv')
df.info()

<ipython-input-1-1907ec29d58a>:2: DtypeWarning: Columns (3,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/concatenated_df.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887261 entries, 0 to 887260
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   DATE                    887261 non-null  int64
 1   SEND_CTPV_NM            887261 non-null  object
 2   SEND_CTPV_CD            887261 non-null  float64
 3   SEND_CTGG_NM            649995 non-null  object
 4   SEND_CTGG_CD            649995 non-null  float64
 5   REC_CTPV_NM             887261 non-null  object
 6   REC_CTPV_CD             887260 non-null  float64
 7   FURNITURE/INTERIOR      887261 non-null  float64
 8   ETC                     887261 non-null  float64
 9   BOOK/RECORD             887261 non-null  float64
 10  DITIGAL/HOME APPLIANCE  887261 non-null  float64
 11  LIFE/HEALTH             887261 non-null  float64
 12  SPORTS                  887261 non-null  float64
 13  FOOD                    887261 non-null  float64
 14  MATERNITY SUPPLIES      887261 non-null  float64
 15  CLOTHING                887261 non-null  float64
 16  MISCELLANEOUS GOODS     887261 non-null  float64
 17  COSTMETICS/BEAUTY       887261 non-null  float64
 18  REC_CTGG_NM             585466 non-null  object
 19  REC_CTGG_CD             585466 non-null  float64
 20  TOTAL                   887261 non-null  float64
dtypes: float64(16), int64(1), object(4)
memory usage: 142.2+ MB

In [2]:
print(df)

            DATE SEND_CTPV_NM  SEND_CTPV_CD SEND_CTGG_NM  SEND_CTGG_CD  \
0       20210108        서울특별시          11.0          노원구       11350.0
1       20210108        서울특별시          11.0          노원구       11350.0
2       20210108        서울특별시          11.0          노원구       11350.0
3       20210108        서울특별시          11.0          노원구       11350.0
4       20210108        서울특별시          11.0          노원구       11350.0
...          ...          ...           ...          ...           ...
887256  20230831        서울특별시          11.0          양천구       11470.0
887257  20230831        서울특별시          11.0          양천구       11470.0
887258  20230831        서울특별시          11.0          양천구       11470.0
887259  20230831        서울특별시          11.0          양천구       11470.0
887260  20230831        서울특별시          11.0          양천구       11470.0

       REC_CTPV_NM  REC_CTPV_CD  FURNITURE/INTERIOR    ETC  BOOK/RECORD  ...  \
0            부산광역시         26.0                60.0  171.0         22.0  ...
1            대구광역시         27.0                42.0  118.0         30.0  ...
2            인천광역시         28.0                73.0  221.0         35.0  ...
3            광주광역시         29.0                22.0   86.0         15.0  ...
4            대전광역시         30.0                37.0   85.0          8.0  ...
...            ...          ...                 ...    ...          ...  ...
887256       서울특별시         11.0                 0.0   21.0          7.0  ...
887257       서울특별시         11.0                 0.0   16.0         11.0  ...
887258       서울특별시         11.0                 3.0   35.0         16.0  ...
887259       서울특별시         11.0                 5.0   28.0         10.0  ...
887260       서울특별시         11.0                 4.0   10.0          4.0  ...

        LIFE/HEALTH  SPORTS   FOOD  MATERNITY SUPPLIES  CLOTHING  \
0             228.0    74.0  127.0                45.0     269.0
1             156.0    39.0  118.0                36.0     197.0
2             230.0    73.0  162.0                49.0     303.0
3              98.0    30.0   81.0                23.0     140.0
4             126.0    37.0   71.0                36.0     143.0
...             ...     ...    ...                 ...       ...
887256         27.0     3.0   10.0                 0.0      13.0
887257         28.0     4.0    7.0                 0.0      16.0
887258         44.0    11.0   10.0                17.0      29.0
887259         30.0     4.0   13.0                 0.0      24.0
887260         19.0     0.0    8.0                 0.0      14.0

        MISCELLANEOUS GOODS  COSTMETICS/BEAUTY  REC_CTGG_NM REC_CTGG_CD  \
0                      96.0               98.0          NaN         NaN
1                      52.0               53.0          NaN         NaN
2                      80.0               89.0          NaN         NaN
3                      39.0               46.0          NaN         NaN
4                      48.0               50.0          NaN         NaN
...                     ...                ...          ...         ...
887256                 19.0                9.0          관악구     11620.0
887257                 17.0                5.0          서초구     11650.0
887258                 37.0               25.0          강남구     11680.0
887259                 20.0               27.0          송파구     11710.0
887260                 11.0               13.0          강동구     11740.0

         TOTAL
0       1256.0
1        893.0
2       1380.0
3        616.0
4        672.0
...        ...
887256   127.0
887257   133.0
887258   244.0
887259   181.0
887260    95.0

[887261 rows x 21 columns]

In [4]:
df['DATE'] = df['DATE'].astype(str)
df['DATE'] = df['DATE'].apply(lambda x: f"{x[:4]}-{x[4:6]}-{x[6:]}")

In [5]:
df['DATE']

0         2021-01-08
1         2021-01-08
2         2021-01-08
3         2021-01-08
4         2021-01-08
             ...
887256    2023-08-31
887257    2023-08-31
887258    2023-08-31
887259    2023-08-31
887260    2023-08-31
Name: DATE, Length: 887261, dtype: object

In [6]:
# 'DATE' 컬럼을 Datetime 형식으로 변환
df['DATE'] = pd.to_datetime(df['DATE'], format='%Y-%m-%d')

df.head()

,DATE,SEND_CTPV_NM,SEND_CTPV_CD,SEND_CTGG_NM,SEND_CTGG_CD,REC_CTPV_NM,REC_CTPV_CD,FURNITURE/INTERIOR,ETC,BOOK/RECORD,...,LIFE/HEALTH,SPORTS,FOOD,MATERNITY SUPPLIES,CLOTHING,MISCELLANEOUS GOODS,COSTMETICS/BEAUTY,REC_CTGG_NM,REC_CTGG_CD,TOTAL
0,2021-01-08,서울특별시,11.0,노원구,11350.0,부산광역시,26.0,60.0,171.0,22.0,...,228.0,74.0,127.0,45.0,269.0,96.0,98.0,NaN,NaN,1256.0
1,2021-01-08,서울특별시,11.0,노원구,11350.0,대구광역시,27.0,42.0,118.0,30.0,...,156.0,39.0,118.0,36.0,197.0,52.0,53.0,NaN,NaN,893.0
2,2021-01-08,서울특별시,11.0,노원구,11350.0,인천광역시,28.0,73.0,221.0,35.0,...,230.0,73.0,162.0,49.0,303.0,80.0,89.0,NaN,NaN,1380.0
3,2021-01-08,서울특별시,11.0,노원구,11350.0,광주광역시,29.0,22.0,86.0,15.0,...,98.0,30.0,81.0,23.0,140.0,39.0,46.0,NaN,NaN,616.0
4,2021-01-08,서울특별시,11.0,노원구,11350.0,대전광역시,30.0,37.0,85.0,8.0,...,126.0,37.0,71.0,36.0,143.0,48.0,50.0,NaN,NaN,672.0

In [7]:
# 'YEAR' 컬럼을 추가
df['YEAR'] = df['DATE'].dt.year

df.head()

,DATE,SEND_CTPV_NM,SEND_CTPV_CD,SEND_CTGG_NM,SEND_CTGG_CD,REC_CTPV_NM,REC_CTPV_CD,FURNITURE/INTERIOR,ETC,BOOK/RECORD,...,SPORTS,FOOD,MATERNITY SUPPLIES,CLOTHING,MISCELLANEOUS GOODS,COSTMETICS/BEAUTY,REC_CTGG_NM,REC_CTGG_CD,TOTAL,YEAR
0,2021-01-08,서울특별시,11.0,노원구,11350.0,부산광역시,26.0,60.0,171.0,22.0,...,74.0,127.0,45.0,269.0,96.0,98.0,NaN,NaN,1256.0,2021
1,2021-01-08,서울특별시,11.0,노원구,11350.0,대구광역시,27.0,42.0,118.0,30.0,...,39.0,118.0,36.0,197.0,52.0,53.0,NaN,NaN,893.0,2021
2,2021-01-08,서울특별시,11.0,노원구,11350.0,인천광역시,28.0,73.0,221.0,35.0,...,73.0,162.0,49.0,303.0,80.0,89.0,NaN,NaN,1380.0,2021
3,2021-01-08,서울특별시,11.0,노원구,11350.0,광주광역시,29.0,22.0,86.0,15.0,...,30.0,81.0,23.0,140.0,39.0,46.0,NaN,NaN,616.0,2021
4,2021-01-08,서울특별시,11.0,노원구,11350.0,대전광역시,30.0,37.0,85.0,8.0,...,37.0,71.0,36.0,143.0,48.0,50.0,NaN,NaN,672.0,2021

## 연도별 요일별 물류량 계산

In [8]:
df['DAY_NAME'] = df['DATE'].dt.day_name()

day_name_mapping = {
    'Monday': '월',
    'Tuesday': '화',
    'Wednesday': '수',
    'Thursday': '목',
    'Friday': '금',
    'Saturday': '토',
    'Sunday': '일'
}

# '요일' 열을 영어에서 한국어로 매핑
df['DAY_NAME'] = df['DAY_NAME'].map(day_name_mapping)
df.head()

,DATE,SEND_CTPV_NM,SEND_CTPV_CD,SEND_CTGG_NM,SEND_CTGG_CD,REC_CTPV_NM,REC_CTPV_CD,FURNITURE/INTERIOR,ETC,BOOK/RECORD,...,FOOD,MATERNITY SUPPLIES,CLOTHING,MISCELLANEOUS GOODS,COSTMETICS/BEAUTY,REC_CTGG_NM,REC_CTGG_CD,TOTAL,YEAR,DAY_NAME
0,2021-01-08,서울특별시,11.0,노원구,11350.0,부산광역시,26.0,60.0,171.0,22.0,...,127.0,45.0,269.0,96.0,98.0,NaN,NaN,1256.0,2021,금
1,2021-01-08,서울특별시,11.0,노원구,11350.0,대구광역시,27.0,42.0,118.0,30.0,...,118.0,36.0,197.0,52.0,53.0,NaN,NaN,893.0,2021,금
2,2021-01-08,서울특별시,11.0,노원구,11350.0,인천광역시,28.0,73.0,221.0,35.0,...,162.0,49.0,303.0,80.0,89.0,NaN,NaN,1380.0,2021,금
3,2021-01-08,서울특별시,11.0,노원구,11350.0,광주광역시,29.0,22.0,86.0,15.0,...,81.0,23.0,140.0,39.0,46.0,NaN,NaN,616.0,2021,금
4,2021-01-08,서울특별시,11.0,노원구,11350.0,대전광역시,30.0,37.0,85.0,8.0,...,71.0,36.0,143.0,48.0,50.0,NaN,NaN,672.0,2021,금

In [9]:
# 연도별 요일별 평균 물류량 계산
average_by_year_day = df.groupby(['YEAR', 'DAY_NAME'])['TOTAL'].mean().reset_index()
average_by_year_day

    YEAR DAY_NAME        TOTAL
0   2021        금  2292.511270
1   2021        목  2545.434040
2   2021        수  2360.938539
3   2021        월  4172.708571
4   2021        일   224.861883
5   2021        토   405.557308
6   2021        화  2781.411775
7   2022        금  1280.047417
8   2022        목  1381.541964
9   2022        수  1387.001570
10  2022        월  2040.526152
11  2022        일   199.196157
12  2022        토   227.913025
13  2022        화  1609.461231
14  2023        금  1124.367074
15  2023        목  1250.552261
16  2023        수  1337.478347
17  2023        월  1876.655433
18  2023        일   181.970922
19  2023        토   198.924244
20  2023        화  1370.088563

In [10]:
average_by_year_day = average_by_year_day.rename(columns={'TOTAL':'DAY_NAME_AVERAGE'})
average_by_year_day

    YEAR DAY_NAME  DAY_NAME_AVERAGE
0   2021        금       2292.511270
1   2021        목       2545.434040
2   2021        수       2360.938539
3   2021        월       4172.708571
4   2021        일        224.861883
5   2021        토        405.557308
6   2021        화       2781.411775
7   2022        금       1280.047417
8   2022        목       1381.541964
9   2022        수       1387.001570
10  2022        월       2040.526152
11  2022        일        199.196157
12  2022        토        227.913025
13  2022        화       1609.461231
14  2023        금       1124.367074
15  2023        목       1250.552261
16  2023        수       1337.478347
17  2023        월       1876.655433
18  2023        일        181.970922
19  2023        토        198.924244
20  2023        화       1370.088563

In [11]:
# 연도별 요일별 평균을 원본 데이터프레임에 추가
df = pd.merge(df, average_by_year_day, on=['YEAR', 'DAY_NAME'], how='left')

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 887261 entries, 0 to 887260
Data columns (total 24 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   DATE                    887261 non-null  datetime64[ns]
 1   SEND_CTPV_NM            887261 non-null  object
 2   SEND_CTPV_CD            887261 non-null  float64
 3   SEND_CTGG_NM            649995 non-null  object
 4   SEND_CTGG_CD            649995 non-null  float64
 5   REC_CTPV_NM             887261 non-null  object
 6   REC_CTPV_CD             887260 non-null  float64
 7   FURNITURE/INTERIOR      887261 non-null  float64
 8   ETC                     887261 non-null  float64
 9   BOOK/RECORD             887261 non-null  float64
 10  DITIGAL/HOME APPLIANCE  887261 non-null  float64
 11  LIFE/HEALTH             887261 non-null  float64
 12  SPORTS                  887261 non-null  float64
 13  FOOD                    887261 non-null  float64
 14  MATERNITY SUPPLIES      887261 non-null  float64
 15  CLOTHING                887261 non-null  float64
 16  MISCELLANEOUS GOODS     887261 non-null  float64
 17  COSTMETICS/BEAUTY       887261 non-null  float64
 18  REC_CTGG_NM             585466 non-null  object
 19  REC_CTGG_CD             585466 non-null  float64
 20  TOTAL                   887261 non-null  float64
 21  YEAR                    887261 non-null  int64
 22  DAY_NAME                887261 non-null  object
 23  DAY_NAME_AVERAGE        887261 non-null  float64
dtypes: datetime64[ns](1), float64(17), int64(1), object(5)
memory usage: 169.2+ MB

In [12]:
df = df.rename(columns={'DITIGAL/HOME APPLIANCE':'DIGITAL/HOME APPLIANCE'})

## 품목별 요일별 물류량 평균 구하기

In [13]:
prod = ['FURNITURE/INTERIOR', 'ETC', 'BOOK/RECORD', 'DIGITAL/HOME APPLIANCE',
                 'LIFE/HEALTH', 'SPORTS', 'FOOD', 'MATERNITY SUPPLIES', 'CLOTHING',
                 'MISCELLANEOUS GOODS', 'COSTMETICS/BEAUTY']

In [14]:
r = df.groupby(['YEAR', 'DAY_NAME']).mean()
result = r[prod].reset_index()
result.head()

<ipython-input-14-6ef2d4e8177a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  r = df.groupby(['YEAR', 'DAY_NAME']).mean()

,YEAR,DAY_NAME,FURNITURE/INTERIOR,ETC,BOOK/RECORD,DIGITAL/HOME APPLIANCE,LIFE/HEALTH,SPORTS,FOOD,MATERNITY SUPPLIES,CLOTHING,MISCELLANEOUS GOODS,COSTMETICS/BEAUTY
0,2021,금,55.935575,304.910406,103.368989,206.254226,332.164444,44.397258,350.825131,56.570060,506.288223,180.872183,150.924775
1,2021,목,62.792096,331.412180,92.925258,237.381921,373.828274,51.789423,409.433849,63.321019,551.848415,200.075697,170.625907
2,2021,수,58.633059,306.881370,93.242374,215.055890,345.350411,47.500822,381.337900,58.426849,512.369224,187.498447,154.642192
3,2021,월,116.064286,519.604196,128.061964,419.303571,697.024107,94.159821,596.495893,104.570179,829.617321,336.071875,331.735357
4,2021,일,3.402767,15.620628,16.646159,10.316387,29.423462,3.614329,50.546058,6.510291,49.713643,18.436846,20.631313

In [15]:
result

,YEAR,DAY_NAME,FURNITURE/INTERIOR,ETC,BOOK/RECORD,DIGITAL/HOME APPLIANCE,LIFE/HEALTH,SPORTS,FOOD,MATERNITY SUPPLIES,CLOTHING,MISCELLANEOUS GOODS,COSTMETICS/BEAUTY
0,2021,금,55.935575,304.910406,103.368989,206.254226,332.164444,44.397258,350.825131,56.570060,506.288223,180.872183,150.924775
1,2021,목,62.792096,331.412180,92.925258,237.381921,373.828274,51.789423,409.433849,63.321019,551.848415,200.075697,170.625907
2,2021,수,58.633059,306.881370,93.242374,215.055890,345.350411,47.500822,381.337900,58.426849,512.369224,187.498447,154.642192
3,2021,월,116.064286,519.604196,128.061964,419.303571,697.024107,94.159821,596.495893,104.570179,829.617321,336.071875,331.735357
4,2021,일,3.402767,15.620628,16.646159,10.316387,29.423462,3.614329,50.546058,6.510291,49.713643,18.436846,20.631313
5,2021,토,5.569251,72.869162,32.312210,14.751961,33.691622,6.734225,83.401693,11.859002,98.211141,29.993226,16.163815
6,2021,화,70.737953,359.561413,95.488225,259.083243,412.190308,55.770018,425.874457,71.691033,615.343931,227.747554,187.923641
7,2022,금,28.859698,215.821156,50.869848,78.508785,168.093503,24.706352,240.407039,27.453921,258.870273,95.631517,90.825325
8,2022,목,30.429816,234.756899,54.347489,86.292242,181.970966,27.521694,269.429897,29.096586,267.823624,100.576656,99.296095
9,2022,수,30.874437,234.120840,55.187785,85.888702,183.441478,27.766702,265.733175,29.463674,273.511672,102.455197,98.557908
10,2022,월,48.416606,377.862902,66.178074,135.003698,282.688222,44.183648,373.149253,41.222596,364.680840,144.913881,162.226432
11,2022,일,2.034196,31.822318,13.909222,4.132968,20.366472,1.892077,66.092734,3.100480,28.056791,10.724989,17.063911
12,2022,토,2.403970,41.686852,15.460471,6.919637,19.974277,3.174866,52.560641,4.310773,51.304606,17.541932,12.575002
13,2022,화,36.236273,284.042902,60.652876,99.804228,212.722149,33.094001,296.341756,34.014324,317.419584,117.587454,117.545683
14,2023,금,26.311980,121.065382,52.647980,77.383577,153.308012,24.831276,212.837638,25.006026,246.196187,94.761086,90.017931
15,2023,목,29.234165,131.028852,57.758336,87.105143,171.012491,28.084291,246.694175,28.219629,268.701694,102.449444,100.264040
16,2023,수,31.514070,139.636992,62.786676,93.322297,186.024714,30.088192,263.274410,30.410307,282.986234,110.356054,107.078400
17,2023,월,47.212025,188.958779,73.550222,139.222135,267.957751,46.214430,366.337190,40.802626,382.284399,153.433442,170.682435
18,2023,일,2.311792,11.642065,19.944708,5.154879,19.950561,2.826608,53.937870,4.579781,30.902538,14.550209,16.169911
19,2023,토,2.316633,21.273793,18.169390,9.249480,19.502362,3.856787,39.292754,3.873992,49.783869,19.222046,12.383137
20,2023,화,32.356973,142.738209,63.028750,93.851765,189.576919,30.822346,269.642276,30.632449,293.492640,110.487889,113.458348

In [16]:
# 연도별 요일별 평균을 원본 데이터프레임에 추가
df2 = pd.merge(df, result, on=['YEAR', 'DAY_NAME'], how='left')

df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 887261 entries, 0 to 887260
Data columns (total 35 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   DATE                      887261 non-null  datetime64[ns]
 1   SEND_CTPV_NM              887261 non-null  object
 2   SEND_CTPV_CD              887261 non-null  float64
 3   SEND_CTGG_NM              649995 non-null  object
 4   SEND_CTGG_CD              649995 non-null  float64
 5   REC_CTPV_NM               887261 non-null  object
 6   REC_CTPV_CD               887260 non-null  float64
 7   FURNITURE/INTERIOR_x      887261 non-null  float64
 8   ETC_x                     887261 non-null  float64
 9   BOOK/RECORD_x             887261 non-null  float64
 10  DIGITAL/HOME APPLIANCE_x  887261 non-null  float64
 11  LIFE/HEALTH_x             887261 non-null  float64
 12  SPORTS_x                  887261 non-null  float64
 13  FOOD_x                    887261 non-null  float64
 14  MATERNITY SUPPLIES_x      887261 non-null  float64
 15  CLOTHING_x                887261 non-null  float64
 16  MISCELLANEOUS GOODS_x     887261 non-null  float64
 17  COSTMETICS/BEAUTY_x       887261 non-null  float64
 18  REC_CTGG_NM               585466 non-null  object
 19  REC_CTGG_CD               585466 non-null  float64
 20  TOTAL                     887261 non-null  float64
 21  YEAR                      887261 non-null  int64
 22  DAY_NAME                  887261 non-null  object
 23  DAY_NAME_AVERAGE          887261 non-null  float64
 24  FURNITURE/INTERIOR_y      887261 non-null  float64
 25  ETC_y                     887261 non-null  float64
 26  BOOK/RECORD_y             887261 non-null  float64
 27  DIGITAL/HOME APPLIANCE_y  887261 non-null  float64
 28  LIFE/HEALTH_y             887261 non-null  float64
 29  SPORTS_y                  887261 non-null  float64
 30  FOOD_y                    887261 non-null  float64
 31  MATERNITY SUPPLIES_y      887261 non-null  float64
 32  CLOTHING_y                887261 non-null  float64
 33  MISCELLANEOUS GOODS_y     887261 non-null  float64
 34  COSTMETICS/BEAUTY_y       887261 non-null  float64
dtypes: datetime64[ns](1), float64(28), int64(1), object(5)
memory usage: 243.7+ MB

In [17]:
df2.head()

,DATE,SEND_CTPV_NM,SEND_CTPV_CD,SEND_CTGG_NM,SEND_CTGG_CD,REC_CTPV_NM,REC_CTPV_CD,FURNITURE/INTERIOR_x,ETC_x,BOOK/RECORD_x,...,ETC_y,BOOK/RECORD_y,DIGITAL/HOME APPLIANCE_y,LIFE/HEALTH_y,SPORTS_y,FOOD_y,MATERNITY SUPPLIES_y,CLOTHING_y,MISCELLANEOUS GOODS_y,COSTMETICS/BEAUTY_y
0,2021-01-08,서울특별시,11.0,노원구,11350.0,부산광역시,26.0,60.0,171.0,22.0,...,304.910406,103.368989,206.254226,332.164444,44.397258,350.825131,56.57006,506.288223,180.872183,150.924775
1,2021-01-08,서울특별시,11.0,노원구,11350.0,대구광역시,27.0,42.0,118.0,30.0,...,304.910406,103.368989,206.254226,332.164444,44.397258,350.825131,56.57006,506.288223,180.872183,150.924775
2,2021-01-08,서울특별시,11.0,노원구,11350.0,인천광역시,28.0,73.0,221.0,35.0,...,304.910406,103.368989,206.254226,332.164444,44.397258,350.825131,56.57006,506.288223,180.872183,150.924775
3,2021-01-08,서울특별시,11.0,노원구,11350.0,광주광역시,29.0,22.0,86.0,15.0,...,304.910406,103.368989,206.254226,332.164444,44.397258,350.825131,56.57006,506.288223,180.872183,150.924775
4,2021-01-08,서울특별시,11.0,노원구,11350.0,대전광역시,30.0,37.0,85.0,8.0,...,304.910406,103.368989,206.254226,332.164444,44.397258,350.825131,56.57006,506.288223,180.872183,150.924775

In [18]:
df2.tail()

,DATE,SEND_CTPV_NM,SEND_CTPV_CD,SEND_CTGG_NM,SEND_CTGG_CD,REC_CTPV_NM,REC_CTPV_CD,FURNITURE/INTERIOR_x,ETC_x,BOOK/RECORD_x,...,ETC_y,BOOK/RECORD_y,DIGITAL/HOME APPLIANCE_y,LIFE/HEALTH_y,SPORTS_y,FOOD_y,MATERNITY SUPPLIES_y,CLOTHING_y,MISCELLANEOUS GOODS_y,COSTMETICS/BEAUTY_y
887256,2023-08-31,서울특별시,11.0,양천구,11470.0,서울특별시,11.0,0.0,21.0,7.0,...,131.028852,57.758336,87.105143,171.012491,28.084291,246.694175,28.219629,268.701694,102.449444,100.26404
887257,2023-08-31,서울특별시,11.0,양천구,11470.0,서울특별시,11.0,0.0,16.0,11.0,...,131.028852,57.758336,87.105143,171.012491,28.084291,246.694175,28.219629,268.701694,102.449444,100.26404
887258,2023-08-31,서울특별시,11.0,양천구,11470.0,서울특별시,11.0,3.0,35.0,16.0,...,131.028852,57.758336,87.105143,171.012491,28.084291,246.694175,28.219629,268.701694,102.449444,100.26404
887259,2023-08-31,서울특별시,11.0,양천구,11470.0,서울특별시,11.0,5.0,28.0,10.0,...,131.028852,57.758336,87.105143,171.012491,28.084291,246.694175,28.219629,268.701694,102.449444,100.26404
887260,2023-08-31,서울특별시,11.0,양천구,11470.0,서울특별시,11.0,4.0,10.0,4.0,...,131.028852,57.758336,87.105143,171.012491,28.084291,246.694175,28.219629,268.701694,102.449444,100.26404

In [19]:
df2.columns = df2.columns.str.replace('_y', '_AVG', regex=True)
df2.columns = df2.columns.str.replace('_x', '', regex=True)
df2.columns

Index(['DATE', 'SEND_CTPV_NM', 'SEND_CTPV_CD', 'SEND_CTGG_NM', 'SEND_CTGG_CD',
       'REC_CTPV_NM', 'REC_CTPV_CD', 'FURNITURE/INTERIOR', 'ETC',
       'BOOK/RECORD', 'DIGITAL/HOME APPLIANCE', 'LIFE/HEALTH', 'SPORTS',
       'FOOD', 'MATERNITY SUPPLIES', 'CLOTHING', 'MISCELLANEOUS GOODS',
       'COSTMETICS/BEAUTY', 'REC_CTGG_NM', 'REC_CTGG_CD', 'TOTAL', 'YEAR',
       'DAY_NAME', 'DAY_NAME_AVERAGE', 'FURNITURE/INTERIOR_AVG', 'ETC_AVG',
       'BOOK/RECORD_AVG', 'DIGITAL/HOME APPLIANCE_AVG', 'LIFE/HEALTH_AVG',
       'SPORTS_AVG', 'FOOD_AVG', 'MATERNITY SUPPLIES_AVG', 'CLOTHING_AVG',
       'MISCELLANEOUS GOODS_AVG', 'COSTMETICS/BEAUTY_AVG'],
      dtype='object')

In [20]:
df2.nunique()

DATE                            820
SEND_CTPV_NM                     18
SEND_CTPV_CD                     18
SEND_CTGG_NM                     25
SEND_CTGG_CD                     25
REC_CTPV_NM                      19
REC_CTPV_CD                      18
FURNITURE/INTERIOR             1602
ETC                            6283
BOOK/RECORD                    3485
DIGITAL/HOME APPLIANCE         3835
LIFE/HEALTH                    6323
SPORTS                         1572
FOOD                           8124
MATERNITY SUPPLIES             1598
CLOTHING                       8038
MISCELLANEOUS GOODS            3727
COSTMETICS/BEAUTY              4794
REC_CTGG_NM                      25
REC_CTGG_CD                      25
TOTAL                         22851
YEAR                              3
DAY_NAME                          7
DAY_NAME_AVERAGE                 21
FURNITURE/INTERIOR_AVG           21
ETC_AVG                          21
BOOK/RECORD_AVG                  21
DIGITAL/HOME APPLIANCE_AVG       21
LIFE/HEALTH_AVG                  21
SPORTS_AVG                       21
FOOD_AVG                         21
MATERNITY SUPPLIES_AVG           21
CLOTHING_AVG                     21
MISCELLANEOUS GOODS_AVG          21
COSTMETICS/BEAUTY_AVG            21
dtype: int64

In [21]:
df2['DATE'].max()

Timestamp('2023-08-31 00:00:00')

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 887261 entries, 0 to 887260
Data columns (total 35 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   DATE                        887261 non-null  datetime64[ns]
 1   SEND_CTPV_NM                887261 non-null  object
 2   SEND_CTPV_CD                887261 non-null  float64
 3   SEND_CTGG_NM                649995 non-null  object
 4   SEND_CTGG_CD                649995 non-null  float64
 5   REC_CTPV_NM                 887261 non-null  object
 6   REC_CTPV_CD                 887260 non-null  float64
 7   FURNITURE/INTERIOR          887261 non-null  float64
 8   ETC                         887261 non-null  float64
 9   BOOK/RECORD                 887261 non-null  float64
 10  DIGITAL/HOME APPLIANCE      887261 non-null  float64
 11  LIFE/HEALTH                 887261 non-null  float64
 12  SPORTS                      887261 non-null  float64
 13  FOOD                        887261 non-null  float64
 14  MATERNITY SUPPLIES          887261 non-null  float64
 15  CLOTHING                    887261 non-null  float64
 16  MISCELLANEOUS GOODS         887261 non-null  float64
 17  COSTMETICS/BEAUTY           887261 non-null  float64
 18  REC_CTGG_NM                 585466 non-null  object
 19  REC_CTGG_CD                 585466 non-null  float64
 20  TOTAL                       887261 non-null  float64
 21  YEAR                        887261 non-null  int64
 22  DAY_NAME                    887261 non-null  object
 23  DAY_NAME_AVERAGE            887261 non-null  float64
 24  FURNITURE/INTERIOR_AVG      887261 non-null  float64
 25  ETC_AVG                     887261 non-null  float64
 26  BOOK/RECORD_AVG             887261 non-null  float64
 27  DIGITAL/HOME APPLIANCE_AVG  887261 non-null  float64
 28  LIFE/HEALTH_AVG             887261 non-null  float64
 29  SPORTS_AVG                  887261 non-null  float64
 30  FOOD_AVG                    887261 non-null  float64
 31  MATERNITY SUPPLIES_AVG      887261 non-null  float64
 32  CLOTHING_AVG                887261 non-null  float64
 33  MISCELLANEOUS GOODS_AVG     887261 non-null  float64
 34  COSTMETICS/BEAUTY_AVG       887261 non-null  float64
dtypes: datetime64[ns](1), float64(28), int64(1), object(5)
memory usage: 243.7+ MB

In [ ]:
df2[place].unique()

AttributeError: ignored

In [29]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 887261 entries, 0 to 887260
Data columns (total 35 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   DATE                        887261 non-null  datetime64[ns]
 1   SEND_CTPV_NM                887261 non-null  object
 2   SEND_CTPV_CD                887261 non-null  float64
 3   SEND_CTGG_NM                649995 non-null  object
 4   SEND_CTGG_CD                649995 non-null  float64
 5   REC_CTPV_NM                 887261 non-null  object
 6   REC_CTPV_CD                 887260 non-null  float64
 7   FURNITURE/INTERIOR          887261 non-null  float64
 8   ETC                         887261 non-null  float64
 9   BOOK/RECORD                 887261 non-null  float64
 10  DIGITAL/HOME APPLIANCE      887261 non-null  float64
 11  LIFE/HEALTH                 887261 non-null  float64
 12  SPORTS                      887261 non-null  float64
 13  FOOD                        887261 non-null  float64
 14  MATERNITY SUPPLIES          887261 non-null  float64
 15  CLOTHING                    887261 non-null  float64
 16  MISCELLANEOUS GOODS         887261 non-null  float64
 17  COSTMETICS/BEAUTY           887261 non-null  float64
 18  REC_CTGG_NM                 585466 non-null  object
 19  REC_CTGG_CD                 585466 non-null  float64
 20  TOTAL                       887261 non-null  float64
 21  YEAR                        887261 non-null  int64
 22  DAY_NAME                    887261 non-null  object
 23  DAY_NAME_AVERAGE            887261 non-null  float64
 24  FURNITURE/INTERIOR_AVG      887261 non-null  float64
 25  ETC_AVG                     887261 non-null  float64
 26  BOOK/RECORD_AVG             887261 non-null  float64
 27  DIGITAL/HOME APPLIANCE_AVG  887261 non-null  float64
 28  LIFE/HEALTH_AVG             887261 non-null  float64
 29  SPORTS_AVG                  887261 non-null  float64
 30  FOOD_AVG                    887261 non-null  float64
 31  MATERNITY SUPPLIES_AVG      887261 non-null  float64
 32  CLOTHING_AVG                887261 non-null  float64
 33  MISCELLANEOUS GOODS_AVG     887261 non-null  float64
 34  COSTMETICS/BEAUTY_AVG       887261 non-null  float64
dtypes: datetime64[ns](1), float64(28), int64(1), object(5)
memory usage: 243.7+ MB

In [32]:
df2['DATE'].max()

Timestamp('2023-08-31 00:00:00')

In [26]:
from google.colab import files

In [31]:
df2.to_csv('df2.csv', encoding='utf-8', index=False)

# 로컬 머신으로 다운로드
from google.colab import files
files.download('df2.csv')