In [1]:
import pandas as pd

연도별 데이터 합치기

In [2]:
cj_21 = pd.read_csv('/content/CJ_21.csv')
print(cj_21)

          DL_YMD SEND_CTPV_NM  SEND_CTPV_CD SEND_CTGG_NM  SEND_CTGG_CD  \
0       20210108        서울특별시          11.0          노원구       11350.0
1       20210108        서울특별시          11.0          노원구       11350.0
2       20210108        서울특별시          11.0          노원구       11350.0
3       20210108        서울특별시          11.0          노원구       11350.0
4       20210108        서울특별시          11.0          노원구       11350.0
...          ...          ...           ...          ...           ...
491667  20211224        서울특별시          11.0          용산구       11170.0
491668  20211224        서울특별시          11.0          용산구       11170.0
491669  20211224        서울특별시          11.0          용산구       11170.0
491670  20211224        서울특별시          11.0          용산구       11170.0
491671  20211224        서울특별시          11.0          용산구       11170.0

       REC_CTPV_NM  REC_CTPV_CD  E_C_01  E_C_02  E_C_03  E_C_04  E_C_05  \
0            부산광역시         26.0    60.0   171.0    22.0    66.0   228.0
1            대구광역시         27.0    42.0   118.0    30.0    52.0   156.0
2            인천광역시         28.0    73.0   221.0    35.0    65.0   230.0
3            광주광역시         29.0    22.0    86.0    15.0    36.0    98.0
4            대전광역시         30.0    37.0    85.0     8.0    31.0   126.0
...            ...          ...     ...     ...     ...     ...     ...
491667       서울특별시         11.0     0.0    55.0    28.0   234.0    55.0
491668       서울특별시         11.0     6.0    71.0    48.0   358.0    82.0
491669       서울특별시         11.0     0.0   130.0    53.0   619.0   107.0
491670       서울특별시         11.0     0.0    83.0    77.0   409.0    72.0
491671       서울특별시         11.0     0.0    44.0    34.0   254.0    49.0

        E_C_06  E_C_07  E_C_08  E_C_09  E_C_10  E_C_11 REC_CTGG_NM  \
0         74.0   127.0    45.0   269.0    96.0    98.0         NaN
1         39.0   118.0    36.0   197.0    52.0    53.0         NaN
2         73.0   162.0    49.0   303.0    80.0    89.0         NaN
3         30.0    81.0    23.0   140.0    39.0    46.0         NaN
4         37.0    71.0    36.0   143.0    48.0    50.0         NaN
...        ...     ...     ...     ...     ...     ...         ...
491667     5.0    21.0     3.0    37.0    61.0    12.0         관악구
491668     3.0    19.0     4.0    52.0    60.0    22.0         서초구
491669    12.0    34.0     7.0    83.0   118.0    27.0         강남구
491670    13.0    29.0     5.0    74.0    83.0    22.0         송파구
491671     5.0    18.0     8.0    25.0    55.0     8.0         강동구

        REC_CTGG_CD
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
491667      11620.0
491668      11650.0
491669      11680.0
491670      11710.0
491671      11740.0

[491672 rows x 20 columns]

<ipython-input-2-94d647748530>:1: DtypeWarning: Columns (3,18) have mixed types. Specify dtype option on import or set low_memory=False.
  cj_21 = pd.read_csv('/content/CJ_21.csv')

In [3]:
new_columns = {'DL_YMD': '배송년월일', 'SEND_CTPV_NM': '발송지_시명','SEND_CTGG_NM': '발송지_구명','SEND_CTGG_CD': '발송지_구코드' ,'SEND_CTPV_CD': '발송지_시코드',  'REC_CTPV_NM':'수신지_시명', 'REC_CTPV_CD': '수신지_시코드', 'REC_CTGG_NM': '수신지_구명', 'REC_CTGG_CD': '수신지_구코드', 'E_C_01': '가구/인테리어', 'E_C_02': '기타', 'E_C_03': '도서/음반','E_C_04': '디지털/가전', 'E_C_05': '생활/건강', 'E_C_06': '스포츠/레저', 'E_C_07': '식품', 'E_C_08': '출산/육아', 'E_C_09': '패션의류', 'E_C_10': '패션잡화', 'E_C_11': '화장품/미용'}
cj_21.rename (columns = new_columns, inplace = True)
print (cj_21)

           배송년월일 발송지_시명  발송지_시코드 발송지_구명  발송지_구코드 수신지_시명  수신지_시코드  가구/인테리어  \
0       20210108  서울특별시     11.0    노원구  11350.0  부산광역시     26.0     60.0
1       20210108  서울특별시     11.0    노원구  11350.0  대구광역시     27.0     42.0
2       20210108  서울특별시     11.0    노원구  11350.0  인천광역시     28.0     73.0
3       20210108  서울특별시     11.0    노원구  11350.0  광주광역시     29.0     22.0
4       20210108  서울특별시     11.0    노원구  11350.0  대전광역시     30.0     37.0
...          ...    ...      ...    ...      ...    ...      ...      ...
491667  20211224  서울특별시     11.0    용산구  11170.0  서울특별시     11.0      0.0
491668  20211224  서울특별시     11.0    용산구  11170.0  서울특별시     11.0      6.0
491669  20211224  서울특별시     11.0    용산구  11170.0  서울특별시     11.0      0.0
491670  20211224  서울특별시     11.0    용산구  11170.0  서울특별시     11.0      0.0
491671  20211224  서울특별시     11.0    용산구  11170.0  서울특별시     11.0      0.0

           기타  도서/음반  디지털/가전  생활/건강  스포츠/레저     식품  출산/육아   패션의류   패션잡화  \
0       171.0   22.0    66.0  228.0    74.0  127.0   45.0  269.0   96.0
1       118.0   30.0    52.0  156.0    39.0  118.0   36.0  197.0   52.0
2       221.0   35.0    65.0  230.0    73.0  162.0   49.0  303.0   80.0
3        86.0   15.0    36.0   98.0    30.0   81.0   23.0  140.0   39.0
4        85.0    8.0    31.0  126.0    37.0   71.0   36.0  143.0   48.0
...       ...    ...     ...    ...     ...    ...    ...    ...    ...
491667   55.0   28.0   234.0   55.0     5.0   21.0    3.0   37.0   61.0
491668   71.0   48.0   358.0   82.0     3.0   19.0    4.0   52.0   60.0
491669  130.0   53.0   619.0  107.0    12.0   34.0    7.0   83.0  118.0
491670   83.0   77.0   409.0   72.0    13.0   29.0    5.0   74.0   83.0
491671   44.0   34.0   254.0   49.0     5.0   18.0    8.0   25.0   55.0

        화장품/미용 수신지_구명  수신지_구코드
0         98.0    NaN      NaN
1         53.0    NaN      NaN
2         89.0    NaN      NaN
3         46.0    NaN      NaN
4         50.0    NaN      NaN
...        ...    ...      ...
491667    12.0    관악구  11620.0
491668    22.0    서초구  11650.0
491669    27.0    강남구  11680.0
491670    22.0    송파구  11710.0
491671     8.0    강동구  11740.0

[491672 rows x 20 columns]

In [4]:
cj_22 = pd.read_csv('/content/CJ_22.csv')
print (cj_22)

<ipython-input-4-c35dd5fda828>:1: DtypeWarning: Columns (3,18) have mixed types. Specify dtype option on import or set low_memory=False.
  cj_22 = pd.read_csv('/content/CJ_22.csv')

          DL_YMD SEND_CTPV_NM  SEND_CTPV_CD SEND_CTGG_NM  SEND_CTGG_CD  \
0       20220104        서울특별시          11.0          동작구       11590.0
1       20220104        서울특별시          11.0          동작구       11590.0
2       20220104        서울특별시          11.0          동작구       11590.0
3       20220104        서울특별시          11.0          동작구       11590.0
4       20220104        서울특별시          11.0          동작구       11590.0
...          ...          ...           ...          ...           ...
489475  20221230        서울특별시          11.0          강남구       11680.0
489476  20221230        서울특별시          11.0          강남구       11680.0
489477  20221230        서울특별시          11.0          강남구       11680.0
489478  20221230        서울특별시          11.0          강남구       11680.0
489479  20221230        서울특별시          11.0          강남구       11680.0

       REC_CTPV_NM  REC_CTPV_CD  E_C_01  E_C_02  E_C_03  E_C_04  E_C_05  \
0            부산광역시         26.0     0.0  1502.0     0.0     0.0     0.0
1            대구광역시         27.0     0.0  1024.0     0.0     0.0     0.0
2            인천광역시         28.0     0.0  1471.0     0.0     0.0     0.0
3            광주광역시         29.0     0.0   500.0     0.0     0.0     7.0
4            대전광역시         30.0     0.0   704.0     0.0     0.0     0.0
...            ...          ...     ...     ...     ...     ...     ...
489475       서울특별시         11.0    12.0    84.0    70.0    27.0    50.0
489476       서울특별시         11.0    19.0   142.0    87.0    30.0    85.0
489477       서울특별시         11.0    20.0   282.0   152.0    60.0   142.0
489478       서울특별시         11.0    12.0   158.0   118.0    36.0   102.0
489479       서울특별시         11.0    11.0    61.0    32.0    33.0    47.0

        E_C_06  E_C_07  E_C_08  E_C_09  E_C_10  E_C_11 REC_CTGG_NM  \
0          0.0    15.0     0.0     0.0     0.0     0.0         NaN
1          0.0     0.0     0.0     0.0     0.0     0.0         NaN
2          0.0     0.0     0.0     0.0     0.0     0.0         NaN
3          0.0    17.0     0.0     0.0     0.0     0.0         NaN
4          0.0     0.0     0.0     0.0     0.0     0.0         NaN
...        ...     ...     ...     ...     ...     ...         ...
489475    14.0   111.0     4.0   229.0    85.0    55.0         관악구
489476    15.0   158.0     9.0   245.0    79.0   139.0         서초구
489477    23.0   289.0    11.0   436.0   163.0   224.0         강남구
489478    23.0   184.0     0.0   321.0   116.0   188.0         송파구
489479     9.0    83.0     5.0   175.0    78.0    36.0         강동구

        REC_CTGG_CD
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
489475      11620.0
489476      11650.0
489477      11680.0
489478      11710.0
489479      11740.0

[489480 rows x 20 columns]

In [5]:
new_columns = {'DL_YMD': '배송년월일', 'SEND_CTPV_NM': '발송지_시명','SEND_CTGG_NM': '발송지_구명','SEND_CTGG_CD': '발송지_구코드' ,'SEND_CTPV_CD': '발송지_시코드',  'REC_CTPV_NM':'수신지_시명', 'REC_CTPV_CD': '수신지_시코드', 'REC_CTGG_NM': '수신지_구명', 'REC_CTGG_CD': '수신지_구코드', 'E_C_01': '가구/인테리어', 'E_C_02': '기타', 'E_C_03': '도서/음반','E_C_04': '디지털/가전', 'E_C_05': '생활/건강', 'E_C_06': '스포츠/레저', 'E_C_07': '식품', 'E_C_08': '출산/육아', 'E_C_09': '패션의류', 'E_C_10': '패션잡화', 'E_C_11': '화장품/미용'}
cj_22.rename (columns = new_columns, inplace = True)
print (cj_22)

           배송년월일 발송지_시명  발송지_시코드 발송지_구명  발송지_구코드 수신지_시명  수신지_시코드  가구/인테리어  \
0       20220104  서울특별시     11.0    동작구  11590.0  부산광역시     26.0      0.0
1       20220104  서울특별시     11.0    동작구  11590.0  대구광역시     27.0      0.0
2       20220104  서울특별시     11.0    동작구  11590.0  인천광역시     28.0      0.0
3       20220104  서울특별시     11.0    동작구  11590.0  광주광역시     29.0      0.0
4       20220104  서울특별시     11.0    동작구  11590.0  대전광역시     30.0      0.0
...          ...    ...      ...    ...      ...    ...      ...      ...
489475  20221230  서울특별시     11.0    강남구  11680.0  서울특별시     11.0     12.0
489476  20221230  서울특별시     11.0    강남구  11680.0  서울특별시     11.0     19.0
489477  20221230  서울특별시     11.0    강남구  11680.0  서울특별시     11.0     20.0
489478  20221230  서울특별시     11.0    강남구  11680.0  서울특별시     11.0     12.0
489479  20221230  서울특별시     11.0    강남구  11680.0  서울특별시     11.0     11.0

            기타  도서/음반  디지털/가전  생활/건강  스포츠/레저     식품  출산/육아   패션의류   패션잡화  \
0       1502.0    0.0     0.0    0.0     0.0   15.0    0.0    0.0    0.0
1       1024.0    0.0     0.0    0.0     0.0    0.0    0.0    0.0    0.0
2       1471.0    0.0     0.0    0.0     0.0    0.0    0.0    0.0    0.0
3        500.0    0.0     0.0    7.0     0.0   17.0    0.0    0.0    0.0
4        704.0    0.0     0.0    0.0     0.0    0.0    0.0    0.0    0.0
...        ...    ...     ...    ...     ...    ...    ...    ...    ...
489475    84.0   70.0    27.0   50.0    14.0  111.0    4.0  229.0   85.0
489476   142.0   87.0    30.0   85.0    15.0  158.0    9.0  245.0   79.0
489477   282.0  152.0    60.0  142.0    23.0  289.0   11.0  436.0  163.0
489478   158.0  118.0    36.0  102.0    23.0  184.0    0.0  321.0  116.0
489479    61.0   32.0    33.0   47.0     9.0   83.0    5.0  175.0   78.0

        화장품/미용 수신지_구명  수신지_구코드
0          0.0    NaN      NaN
1          0.0    NaN      NaN
2          0.0    NaN      NaN
3          0.0    NaN      NaN
4          0.0    NaN      NaN
...        ...    ...      ...
489475    55.0    관악구  11620.0
489476   139.0    서초구  11650.0
489477   224.0    강남구  11680.0
489478   188.0    송파구  11710.0
489479    36.0    강동구  11740.0

[489480 rows x 20 columns]

In [6]:
cj_23 = pd.read_csv('/content/CJ_23.csv')
print(cj_23)

          DL_YMD SEND_CTPV_NM  SEND_CTPV_CD SEND_CTGG_NM  SEND_CTGG_CD  \
0       20230109        서울특별시          11.0          광진구       11215.0
1       20230109        서울특별시          11.0          광진구       11215.0
2       20230109        서울특별시          11.0          광진구       11215.0
3       20230109        서울특별시          11.0          광진구       11215.0
4       20230109        서울특별시          11.0          광진구       11215.0
...          ...          ...           ...          ...           ...
323351  20230831        서울특별시          11.0          양천구       11470.0
323352  20230831        서울특별시          11.0          양천구       11470.0
323353  20230831        서울특별시          11.0          양천구       11470.0
323354  20230831        서울특별시          11.0          양천구       11470.0
323355  20230831        서울특별시          11.0          양천구       11470.0

       REC_CTPV_NM  REC_CTPV_CD  E_C_01  E_C_02  E_C_03  E_C_04  E_C_05  \
0            부산광역시         26.0    47.0   290.0    55.0   206.0   441.0
1            대구광역시         27.0    52.0   221.0    39.0   137.0   278.0
2            인천광역시         28.0    64.0   304.0    64.0   213.0   423.0
3            광주광역시         29.0    28.0   143.0    23.0   103.0   216.0
4            대전광역시         30.0    31.0   151.0    25.0   109.0   201.0
...            ...          ...     ...     ...     ...     ...     ...
323351       서울특별시         11.0     0.0    21.0     7.0    18.0    27.0
323352       서울특별시         11.0     0.0    16.0    11.0    29.0    28.0
323353       서울특별시         11.0     3.0    35.0    16.0    17.0    44.0
323354       서울특별시         11.0     5.0    28.0    10.0    20.0    30.0
323355       서울특별시         11.0     4.0    10.0     4.0    12.0    19.0

        E_C_06  E_C_07  E_C_08  E_C_09  E_C_10  E_C_11 REC_CTGG_NM  \
0         82.0   206.0    81.0   635.0   406.0    89.0         NaN
1         67.0   152.0    45.0   434.0   339.0    74.0         NaN
2         93.0   200.0    90.0   639.0   447.0    78.0         NaN
3         40.0    98.0    42.0   336.0   219.0    30.0         NaN
4         53.0    78.0    37.0   305.0   177.0    44.0         NaN
...        ...     ...     ...     ...     ...     ...         ...
323351     3.0    10.0     0.0    13.0    19.0     9.0         관악구
323352     4.0     7.0     0.0    16.0    17.0     5.0         서초구
323353    11.0    10.0    17.0    29.0    37.0    25.0         강남구
323354     4.0    13.0     0.0    24.0    20.0    27.0         송파구
323355     0.0     8.0     0.0    14.0    11.0    13.0         강동구

        REC_CTGG_CD
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
323351      11620.0
323352      11650.0
323353      11680.0
323354      11710.0
323355      11740.0

[323356 rows x 20 columns]

<ipython-input-6-f196923244bc>:1: DtypeWarning: Columns (3,18) have mixed types. Specify dtype option on import or set low_memory=False.
  cj_23 = pd.read_csv('/content/CJ_23.csv')

In [9]:
new_columns = {'DL_YMD': '배송년월일', 'SEND_CTPV_NM': '발송지_시명','SEND_CTGG_NM': '발송지_구명','SEND_CTGG_CD': '발송지_구코드' ,'SEND_CTPV_CD': '발송지_시코드',  'REC_CTPV_NM':'수신지_시명', 'REC_CTPV_CD': '수신지_시코드', 'REC_CTGG_NM': '수신지_구명', 'REC_CTGG_CD': '수신지_구코드', 'E_C_01': '가구/인테리어', 'E_C_02': '기타', 'E_C_03': '도서/음반','E_C_04': '디지털/가전', 'E_C_05': '생활/건강', 'E_C_06': '스포츠/레저', 'E_C_07': '식품', 'E_C_08': '출산/육아', 'E_C_09': '패션의류', 'E_C_10': '패션잡화', 'E_C_11': '화장품/미용'}
cj_23.rename (columns = new_columns, inplace = True)
print (cj_23)

           배송년월일 발송지_시명  발송지_시코드 발송지_구명  발송지_구코드 수신지_시명  수신지_시코드  가구/인테리어  \
0       20230109  서울특별시     11.0    광진구  11215.0  부산광역시     26.0     47.0
1       20230109  서울특별시     11.0    광진구  11215.0  대구광역시     27.0     52.0
2       20230109  서울특별시     11.0    광진구  11215.0  인천광역시     28.0     64.0
3       20230109  서울특별시     11.0    광진구  11215.0  광주광역시     29.0     28.0
4       20230109  서울특별시     11.0    광진구  11215.0  대전광역시     30.0     31.0
...          ...    ...      ...    ...      ...    ...      ...      ...
323351  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
323352  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
323353  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      3.0
323354  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      5.0
323355  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      4.0

           기타  도서/음반  디지털/가전  생활/건강  스포츠/레저     식품  출산/육아   패션의류   패션잡화  \
0       290.0   55.0   206.0  441.0    82.0  206.0   81.0  635.0  406.0
1       221.0   39.0   137.0  278.0    67.0  152.0   45.0  434.0  339.0
2       304.0   64.0   213.0  423.0    93.0  200.0   90.0  639.0  447.0
3       143.0   23.0   103.0  216.0    40.0   98.0   42.0  336.0  219.0
4       151.0   25.0   109.0  201.0    53.0   78.0   37.0  305.0  177.0
...       ...    ...     ...    ...     ...    ...    ...    ...    ...
323351   21.0    7.0    18.0   27.0     3.0   10.0    0.0   13.0   19.0
323352   16.0   11.0    29.0   28.0     4.0    7.0    0.0   16.0   17.0
323353   35.0   16.0    17.0   44.0    11.0   10.0   17.0   29.0   37.0
323354   28.0   10.0    20.0   30.0     4.0   13.0    0.0   24.0   20.0
323355   10.0    4.0    12.0   19.0     0.0    8.0    0.0   14.0   11.0

        화장품/미용 수신지_구명  수신지_구코드
0         89.0    NaN      NaN
1         74.0    NaN      NaN
2         78.0    NaN      NaN
3         30.0    NaN      NaN
4         44.0    NaN      NaN
...        ...    ...      ...
323351     9.0    관악구  11620.0
323352     5.0    서초구  11650.0
323353    25.0    강남구  11680.0
323354    27.0    송파구  11710.0
323355    13.0    강동구  11740.0

[323356 rows x 20 columns]

In [10]:
cj_23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 323356 entries, 0 to 323355
Data columns (total 20 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   배송년월일    323356 non-null  int64
 1   발송지_시명   323356 non-null  object
 2   발송지_시코드  323356 non-null  float64
 3   발송지_구명   228617 non-null  object
 4   발송지_구코드  228617 non-null  float64
 5   수신지_시명   323356 non-null  object
 6   수신지_시코드  323356 non-null  float64
 7   가구/인테리어  323356 non-null  float64
 8   기타       323356 non-null  float64
 9   도서/음반    323356 non-null  float64
 10  디지털/가전   323356 non-null  float64
 11  생활/건강    323356 non-null  float64
 12  스포츠/레저   323356 non-null  float64
 13  식품       323356 non-null  float64
 14  출산/육아    323356 non-null  float64
 15  패션의류     323356 non-null  float64
 16  패션잡화     323356 non-null  float64
 17  화장품/미용   323356 non-null  float64
 18  수신지_구명   233095 non-null  object
 19  수신지_구코드  233095 non-null  float64
dtypes: float64(15), int64(1), object(4)
memory usage: 49.3+ MB

In [11]:
concatenated_df = pd.concat([cj_21, cj_22, cj_23], ignore_index=True)
print (concatenated_df)

            배송년월일 발송지_시명  발송지_시코드 발송지_구명  발송지_구코드 수신지_시명  수신지_시코드  가구/인테리어  \
0        20210108  서울특별시     11.0    노원구  11350.0  부산광역시     26.0     60.0
1        20210108  서울특별시     11.0    노원구  11350.0  대구광역시     27.0     42.0
2        20210108  서울특별시     11.0    노원구  11350.0  인천광역시     28.0     73.0
3        20210108  서울특별시     11.0    노원구  11350.0  광주광역시     29.0     22.0
4        20210108  서울특별시     11.0    노원구  11350.0  대전광역시     30.0     37.0
...           ...    ...      ...    ...      ...    ...      ...      ...
1304503  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
1304504  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
1304505  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      3.0
1304506  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      5.0
1304507  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      4.0

            기타  도서/음반  디지털/가전  생활/건강  스포츠/레저     식품  출산/육아   패션의류  패션잡화  \
0        171.0   22.0    66.0  228.0    74.0  127.0   45.0  269.0  96.0
1        118.0   30.0    52.0  156.0    39.0  118.0   36.0  197.0  52.0
2        221.0   35.0    65.0  230.0    73.0  162.0   49.0  303.0  80.0
3         86.0   15.0    36.0   98.0    30.0   81.0   23.0  140.0  39.0
4         85.0    8.0    31.0  126.0    37.0   71.0   36.0  143.0  48.0
...        ...    ...     ...    ...     ...    ...    ...    ...   ...
1304503   21.0    7.0    18.0   27.0     3.0   10.0    0.0   13.0  19.0
1304504   16.0   11.0    29.0   28.0     4.0    7.0    0.0   16.0  17.0
1304505   35.0   16.0    17.0   44.0    11.0   10.0   17.0   29.0  37.0
1304506   28.0   10.0    20.0   30.0     4.0   13.0    0.0   24.0  20.0
1304507   10.0    4.0    12.0   19.0     0.0    8.0    0.0   14.0  11.0

         화장품/미용 수신지_구명  수신지_구코드
0          98.0    NaN      NaN
1          53.0    NaN      NaN
2          89.0    NaN      NaN
3          46.0    NaN      NaN
4          50.0    NaN      NaN
...         ...    ...      ...
1304503     9.0    관악구  11620.0
1304504     5.0    서초구  11650.0
1304505    25.0    강남구  11680.0
1304506    27.0    송파구  11710.0
1304507    13.0    강동구  11740.0

[1304508 rows x 20 columns]

In [12]:
concatenated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1304508 entries, 0 to 1304507
Data columns (total 20 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   배송년월일    1304508 non-null  int64
 1   발송지_시명   1304508 non-null  object
 2   발송지_시코드  1304508 non-null  float64
 3   발송지_구명   924411 non-null   object
 4   발송지_구코드  924411 non-null   float64
 5   수신지_시명   1304508 non-null  object
 6   수신지_시코드  1304508 non-null  float64
 7   가구/인테리어  1304508 non-null  float64
 8   기타       1304508 non-null  float64
 9   도서/음반    1304508 non-null  float64
 10  디지털/가전   1304508 non-null  float64
 11  생활/건강    1304508 non-null  float64
 12  스포츠/레저   1304508 non-null  float64
 13  식품       1304508 non-null  float64
 14  출산/육아    1304508 non-null  float64
 15  패션의류     1304508 non-null  float64
 16  패션잡화     1304508 non-null  float64
 17  화장품/미용   1304508 non-null  float64
 18  수신지_구명   939171 non-null   object
 19  수신지_구코드  939171 non-null   float64
dtypes: float64(15), int64(1), object(4)
memory usage: 199.1+ MB

In [ ]:
from google.colab import files
concatenated_df = pd.concat([cj_21, cj_22, cj_23], ignore_index=True)
concatenated_df.to_csv('concatenated_data.csv', index=False)
files.download("concatenated_data.csv")

총물량 구하기

In [13]:
columns_to_sum = ['가구/인테리어','기타', '도서/음반', '디지털/가전', '생활/건강', '스포츠/레저', '식품', '출산/육아', '패션의류', '패션잡화', '화장품/미용']
concatenated_df['총물량'] = concatenated_df[columns_to_sum].sum(axis=1)
print (concatenated_df)

            배송년월일 발송지_시명  발송지_시코드 발송지_구명  발송지_구코드 수신지_시명  수신지_시코드  가구/인테리어  \
0        20210108  서울특별시     11.0    노원구  11350.0  부산광역시     26.0     60.0
1        20210108  서울특별시     11.0    노원구  11350.0  대구광역시     27.0     42.0
2        20210108  서울특별시     11.0    노원구  11350.0  인천광역시     28.0     73.0
3        20210108  서울특별시     11.0    노원구  11350.0  광주광역시     29.0     22.0
4        20210108  서울특별시     11.0    노원구  11350.0  대전광역시     30.0     37.0
...           ...    ...      ...    ...      ...    ...      ...      ...
1304503  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
1304504  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
1304505  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      3.0
1304506  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      5.0
1304507  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      4.0

            기타  도서/음반  ...  생활/건강  스포츠/레저     식품  출산/육아   패션의류  패션잡화  화장품/미용  \
0        171.0   22.0  ...  228.0    74.0  127.0   45.0  269.0  96.0    98.0
1        118.0   30.0  ...  156.0    39.0  118.0   36.0  197.0  52.0    53.0
2        221.0   35.0  ...  230.0    73.0  162.0   49.0  303.0  80.0    89.0
3         86.0   15.0  ...   98.0    30.0   81.0   23.0  140.0  39.0    46.0
4         85.0    8.0  ...  126.0    37.0   71.0   36.0  143.0  48.0    50.0
...        ...    ...  ...    ...     ...    ...    ...    ...   ...     ...
1304503   21.0    7.0  ...   27.0     3.0   10.0    0.0   13.0  19.0     9.0
1304504   16.0   11.0  ...   28.0     4.0    7.0    0.0   16.0  17.0     5.0
1304505   35.0   16.0  ...   44.0    11.0   10.0   17.0   29.0  37.0    25.0
1304506   28.0   10.0  ...   30.0     4.0   13.0    0.0   24.0  20.0    27.0
1304507   10.0    4.0  ...   19.0     0.0    8.0    0.0   14.0  11.0    13.0

         수신지_구명  수신지_구코드     총물량
0           NaN      NaN  1256.0
1           NaN      NaN   893.0
2           NaN      NaN  1380.0
3           NaN      NaN   616.0
4           NaN      NaN   672.0
...         ...      ...     ...
1304503     관악구  11620.0   127.0
1304504     서초구  11650.0   133.0
1304505     강남구  11680.0   244.0
1304506     송파구  11710.0   181.0
1304507     강동구  11740.0    95.0

[1304508 rows x 21 columns]

In [ ]:
concatenated_df.to_csv('concatenated_data.csv',encoding = 'utf-8', index=False)
from google.colab import files
files.download('concatenated_data.csv')

In [15]:
print(concatenated_df)

            배송년월일 발송지_시명  발송지_시코드 발송지_구명  발송지_구코드 수신지_시명  수신지_시코드  가구/인테리어  \
0        20210108  서울특별시     11.0    노원구  11350.0  부산광역시     26.0     60.0
1        20210108  서울특별시     11.0    노원구  11350.0  대구광역시     27.0     42.0
2        20210108  서울특별시     11.0    노원구  11350.0  인천광역시     28.0     73.0
3        20210108  서울특별시     11.0    노원구  11350.0  광주광역시     29.0     22.0
4        20210108  서울특별시     11.0    노원구  11350.0  대전광역시     30.0     37.0
...           ...    ...      ...    ...      ...    ...      ...      ...
1304503  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
1304504  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      0.0
1304505  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      3.0
1304506  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      5.0
1304507  20230831  서울특별시     11.0    양천구  11470.0  서울특별시     11.0      4.0

            기타  도서/음반  ...  생활/건강  스포츠/레저     식품  출산/육아   패션의류  패션잡화  화장품/미용  \
0        171.0   22.0  ...  228.0    74.0  127.0   45.0  269.0  96.0    98.0
1        118.0   30.0  ...  156.0    39.0  118.0   36.0  197.0  52.0    53.0
2        221.0   35.0  ...  230.0    73.0  162.0   49.0  303.0  80.0    89.0
3         86.0   15.0  ...   98.0    30.0   81.0   23.0  140.0  39.0    46.0
4         85.0    8.0  ...  126.0    37.0   71.0   36.0  143.0  48.0    50.0
...        ...    ...  ...    ...     ...    ...    ...    ...   ...     ...
1304503   21.0    7.0  ...   27.0     3.0   10.0    0.0   13.0  19.0     9.0
1304504   16.0   11.0  ...   28.0     4.0    7.0    0.0   16.0  17.0     5.0
1304505   35.0   16.0  ...   44.0    11.0   10.0   17.0   29.0  37.0    25.0
1304506   28.0   10.0  ...   30.0     4.0   13.0    0.0   24.0  20.0    27.0
1304507   10.0    4.0  ...   19.0     0.0    8.0    0.0   14.0  11.0    13.0

         수신지_구명  수신지_구코드     총물량
0           NaN      NaN  1256.0
1           NaN      NaN   893.0
2           NaN      NaN  1380.0
3           NaN      NaN   616.0
4           NaN      NaN   672.0
...         ...      ...     ...
1304503     관악구  11620.0   127.0
1304504     서초구  11650.0   133.0
1304505     강남구  11680.0   244.0
1304506     송파구  11710.0   181.0
1304507     강동구  11740.0    95.0

[1304508 rows x 21 columns]

In [16]:
new_columns = {'배송년월일': 'DATE', '발송지_시명': 'SEND_CTPV_NM','발송지_구명': 'SEND_CTGG_NM','발송지_구코드': 'SEND_CTGG_CD' ,'발송지_시코드': 'SEND_CTPV_CD',  '수신지_시명':'REC_CTPV_NM', '수신지_시코드': 'REC_CTPV_CD', '수신지_구명': 'REC_CTGG_NM', '수신지_구코드': 'REC_CTGG_CD', '가구/인테리어': 'FURNITURE/INTERIOR', '기타': 'ETC', '도서/음반': 'BOOK/RECORD','디지털/가전': 'DITIGAL/HOME APPLIANCE', '생활/건강': 'LIFE/HEALTH', '스포츠/레저': 'SPORTS', '식품': 'FOOD', '출산/육아': 'MATERNITY SUPPLIES', '패션의류': 'CLOTHING', '패션잡화': 'MISCELLANEOUS GOODS', '화장품/미용': 'COSTMETICS/BEAUTY', '총물량': 'TOTAL'}
concatenated_df.rename (columns = new_columns, inplace = True)
print (concatenated_df)

             DATE SEND_CTPV_NM  SEND_CTPV_CD SEND_CTGG_NM  SEND_CTGG_CD  \
0        20210108        서울특별시          11.0          노원구       11350.0
1        20210108        서울특별시          11.0          노원구       11350.0
2        20210108        서울특별시          11.0          노원구       11350.0
3        20210108        서울특별시          11.0          노원구       11350.0
4        20210108        서울특별시          11.0          노원구       11350.0
...           ...          ...           ...          ...           ...
1304503  20230831        서울특별시          11.0          양천구       11470.0
1304504  20230831        서울특별시          11.0          양천구       11470.0
1304505  20230831        서울특별시          11.0          양천구       11470.0
1304506  20230831        서울특별시          11.0          양천구       11470.0
1304507  20230831        서울특별시          11.0          양천구       11470.0

        REC_CTPV_NM  REC_CTPV_CD  FURNITURE/INTERIOR    ETC  BOOK/RECORD  ...  \
0             부산광역시         26.0                60.0  171.0         22.0  ...
1             대구광역시         27.0                42.0  118.0         30.0  ...
2             인천광역시         28.0                73.0  221.0         35.0  ...
3             광주광역시         29.0                22.0   86.0         15.0  ...
4             대전광역시         30.0                37.0   85.0          8.0  ...
...             ...          ...                 ...    ...          ...  ...
1304503       서울특별시         11.0                 0.0   21.0          7.0  ...
1304504       서울특별시         11.0                 0.0   16.0         11.0  ...
1304505       서울특별시         11.0                 3.0   35.0         16.0  ...
1304506       서울특별시         11.0                 5.0   28.0         10.0  ...
1304507       서울특별시         11.0                 4.0   10.0          4.0  ...

         LIFE/HEALTH  SPORTS   FOOD  MATERNITY SUPPLIES  CLOTHING  \
0              228.0    74.0  127.0                45.0     269.0
1              156.0    39.0  118.0                36.0     197.0
2              230.0    73.0  162.0                49.0     303.0
3               98.0    30.0   81.0                23.0     140.0
4              126.0    37.0   71.0                36.0     143.0
...              ...     ...    ...                 ...       ...
1304503         27.0     3.0   10.0                 0.0      13.0
1304504         28.0     4.0    7.0                 0.0      16.0
1304505         44.0    11.0   10.0                17.0      29.0
1304506         30.0     4.0   13.0                 0.0      24.0
1304507         19.0     0.0    8.0                 0.0      14.0

         MISCELLANEOUS GOODS  COSTMETICS/BEAUTY  REC_CTGG_NM REC_CTGG_CD  \
0                       96.0               98.0          NaN         NaN
1                       52.0               53.0          NaN         NaN
2                       80.0               89.0          NaN         NaN
3                       39.0               46.0          NaN         NaN
4                       48.0               50.0          NaN         NaN
...                      ...                ...          ...         ...
1304503                 19.0                9.0          관악구     11620.0
1304504                 17.0                5.0          서초구     11650.0
1304505                 37.0               25.0          강남구     11680.0
1304506                 20.0               27.0          송파구     11710.0
1304507                 11.0               13.0          강동구     11740.0

          TOTAL
0        1256.0
1         893.0
2        1380.0
3         616.0
4         672.0
...         ...
1304503   127.0
1304504   133.0
1304505   244.0
1304506   181.0
1304507    95.0

[1304508 rows x 21 columns]

데이터 타입 변경

In [18]:
print (type (concatenated_df.SEND_CTPV_CD))

<class 'pandas.core.series.Series'>

In [17]:
columns_to_convert = ['DATE', 'SEND_CTGG_CD', 'SEND_CTPV_CD', 'REC_CTPV_CD', 'REC_CTGG_CD', 'FURNITURE/INTERIOR', 'ETC', 'BOOK/RECORD', 'DITIGAL/HOME APPLIANCE', 'LIFE/HEALTH', 'SPORTS', 'FOOD', 'MATERNITY SUPPLIES', 'CLOTHING', 'MISCELLANEOUS GOODS', 'COSTMETICS/BEAUTY', 'TOTAL']
concatenated_df[columns_to_convert] = concatenated_df[columns_to_convert].apply(pd.to_numeric, errors='coerce').astype('Int64')
print(concatenated_df)

             DATE SEND_CTPV_NM  SEND_CTPV_CD SEND_CTGG_NM  SEND_CTGG_CD  \
0        20210108        서울특별시            11          노원구         11350
1        20210108        서울특별시            11          노원구         11350
2        20210108        서울특별시            11          노원구         11350
3        20210108        서울특별시            11          노원구         11350
4        20210108        서울특별시            11          노원구         11350
...           ...          ...           ...          ...           ...
1304503  20230831        서울특별시            11          양천구         11470
1304504  20230831        서울특별시            11          양천구         11470
1304505  20230831        서울특별시            11          양천구         11470
1304506  20230831        서울특별시            11          양천구         11470
1304507  20230831        서울특별시            11          양천구         11470

        REC_CTPV_NM  REC_CTPV_CD  FURNITURE/INTERIOR  ETC  BOOK/RECORD  ...  \
0             부산광역시           26                  60  171           22  ...
1             대구광역시           27                  42  118           30  ...
2             인천광역시           28                  73  221           35  ...
3             광주광역시           29                  22   86           15  ...
4             대전광역시           30                  37   85            8  ...
...             ...          ...                 ...  ...          ...  ...
1304503       서울특별시           11                   0   21            7  ...
1304504       서울특별시           11                   0   16           11  ...
1304505       서울특별시           11                   3   35           16  ...
1304506       서울특별시           11                   5   28           10  ...
1304507       서울특별시           11                   4   10            4  ...

         LIFE/HEALTH  SPORTS  FOOD  MATERNITY SUPPLIES  CLOTHING  \
0                228      74   127                  45       269
1                156      39   118                  36       197
2                230      73   162                  49       303
3                 98      30    81                  23       140
4                126      37    71                  36       143
...              ...     ...   ...                 ...       ...
1304503           27       3    10                   0        13
1304504           28       4     7                   0        16
1304505           44      11    10                  17        29
1304506           30       4    13                   0        24
1304507           19       0     8                   0        14

         MISCELLANEOUS GOODS  COSTMETICS/BEAUTY  REC_CTGG_NM REC_CTGG_CD  \
0                         96                 98          NaN        <NA>
1                         52                 53          NaN        <NA>
2                         80                 89          NaN        <NA>
3                         39                 46          NaN        <NA>
4                         48                 50          NaN        <NA>
...                      ...                ...          ...         ...
1304503                   19                  9          관악구       11620
1304504                   17                  5          서초구       11650
1304505                   37                 25          강남구       11680
1304506                   20                 27          송파구       11710
1304507                   11                 13          강동구       11740

         TOTAL
0         1256
1          893
2         1380
3          616
4          672
...        ...
1304503    127
1304504    133
1304505    244
1304506    181
1304507     95

[1304508 rows x 21 columns]

In [ ]:
concatenated_df.to_csv('concatenated_data.csv',encoding = 'utf-8', index=False)
from google.colab import files
files.download('concatenated_data.csv')